# Generated by Django 3.0.5 on 2020-04-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousinscription',
            name='curriculum',
            field=models.FileField(default=1, upload_to='jobcall/curriculums'),
            preserve_default=False,
        ),
    ]
