# Generated by Django 3.0.5 on 2020-05-02 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobcall', '0002_anonymousinscription_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousinscription',
            name='curriculum',
            field=models.FileField(upload_to='jobcall/curriculums', verbose_name='curriculum'),
        ),
        migrations.AlterField(
            model_name='jobcall',
            name='aspirants',
            field=models.ManyToManyField(blank=True, related_name='jobcall_aspirant', to=settings.AUTH_USER_MODEL, verbose_name='aspirants'),
        ),
        migrations.AlterField(
            model_name='jobcall',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='company'),
        ),
    ]
