# Generated by Django 3.0.5 on 2020-04-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'aspiring'), (2, 'company'), (3, 'admin')], default=1, verbose_name='rol'),
        ),
    ]
